### ISSUE TITLE
Formating number

### ISSUE THREAD

**Issue by walliscz** [willemdh/check_ms_win_disk_load#1]
Hi,
I think that is not a good idea:

$DiskStruct.AvgDiskReadQueueValue = '{0:N5}' -f ($AvgObjDiskReadQueueValues.average)
etc.

befor:
  Read/s = 2205.06046082681
after:
  Read/s = 2,205.06046

because:

(Get-Culture).NumberFormat.CurrencyGroupSeparator
,

it might be better:
$DiskStruct.AvgDiskReadQueueValue = [math]::Round($AvgObjDiskReadQueueValues.average, 5)

**Comment by willemdh** [comment]
Hey Walliscz,

You definitely have a point. It does seem more logical. I'll look into it asap, but might take some time. Thanks for making the issue!

Grtz

Willem

**Comment by willemdh** [comment]
@walliscz I made some changes to the plugin. I found some other small bugs in the output and a big bug with the latency. I fear I missed the ball with the latency and outputted in us while it should in fact be ms. It would be nice is someone could verify my logic and confirm.. :)

**Comment by willemdh** [comment]
Fixed with

```powershell
	$OldCulture = [System.Threading.Thread]::CurrentThread.CurrentCulture
	[System.Threading.Thread]::CurrentThread.CurrentCulture = 'en-US'
	$DiskStruct.AvgDiskSecReadValue = [decimal]('{0:N5}' -f ($AvgObjDiskSecReadValues.average * 1000))
	$DiskStruct.AvgDiskSecWriteValue = [decimal]('{0:N5}' -f ($AvgObjDiskSecWriteValues.average * 1000))
    $DiskStruct.AvgDiskReadQueueValue = [decimal]('{0:N5}' -f ($AvgObjDiskReadQueueValues.average))
    $DiskStruct.AvgDiskWriteQueueValue = [decimal]('{0:N5}' -f ($AvgObjDiskWriteQueueValues.average))
    $DiskStruct.DiskReadsSecValue = [decimal]('{0:N5}' -f ($AvgObjDiskReadsSecValues.average))
    $DiskStruct.DiskWritesSecValue = [decimal]('{0:N5}' -f ($AvgObjDiskWritesSecValues.average))
    $DiskStruct.DiskReadBytesSecValue = [decimal]('{0:N5}' -f ($AvgObjDiskReadBytesSecValues.average / 1024 / 1024))
    $DiskStruct.DiskWriteBytesSecValue = [decimal]('{0:N5}' -f ($AvgObjDiskWriteBytesSecValues.average / 1024 / 1024))
	[System.Threading.Thread]::CurrentThread.CurrentCulture = $OldCulture
```
