### ISSUE TITLE
icinga2 - invalid performance data

### ISSUE THREAD

**Issue by andreasfenzsw** [willemdh/check_ms_win_disk_load#3]
Hello 

icinga[2] does not recognize all UOMs in perfdata. See [http://docs.icinga.org/latest/en/perfdata.html](http://docs.icinga.org/latest/en/perfdata.html)

changing to

`	$DiskStruct.ReturnString += "'Read_Latency'=$($DiskStruct.AvgDiskSecReadValue)ms "
	$DiskStruct.ReturnString += "'Write_Latency'=$($DiskStruct.AvgDiskSecWriteValue)ms "
	$DiskStruct.ReturnString += "'Read_Queue'=$($DiskStruct.AvgDiskReadQueueValue) "
	$DiskStruct.ReturnString += "'Write_Queue'=$($DiskStruct.AvgDiskWriteQueueValue) "
	$DiskStruct.ReturnString += "'Number_of_Reads'=$($DiskStruct.DiskReadsSecValue) "
	$DiskStruct.ReturnString += "'Number_of_Writes'=$($DiskStruct.DiskWritesSecValue) "
	$DiskStruct.ReturnString += "'Read_Rate'=$($DiskStruct.DiskReadBytesSecValue)MB "
	$DiskStruct.ReturnString += "'Write_Rate'=$($DiskStruct.DiskWriteBytesSecValue)MB "	`

solved my problem.

I don´t know if the script is intended to work with icinga. I just want to mention.

Thanks for your work!
Andreas

**Comment by willemdh** [comment]
Andreas, 
It seems the UOM's do work with Highcharts in Nagios XI. So I prefer to leave this as it is for now:
![image](https://cloud.githubusercontent.com/assets/6462991/13144407/bab3dc16-d64a-11e5-9b18-708af884706d.png)
Thanks for letting me know though.
Grtz
